### ISSUE TITLE
project & list & task 排版修正

### ISSUE THREAD

**Issue by Liu-Yun-Syuan** [astrocamp/15th-SyncSquad#142]
# project
● project index
- [x] 在員工建立時，為每個員工建立「範例專案」
   - [x] 包含「範例列表」
       - [x] 包含「範例任務」
- [x] 表格
    - [x] 沒有專案時
        - [x] 顯示「沒有專案」的提示
        - [x] 顯示「新增專案」按鈕
    - [x] hover & 連結 效果
        - [ ] 選項一：tr 維持整列 hover，並且點擊整個 tr 就可以進入專案
        - [x] 選項二：tr 沒有 hover 效果，只有 title hover 會有底線

● project _header
- [x] 視圖切換按鈕
    - [x] kanban 時，不顯示 kanban，手機版要放大才好按
    - [x] calendar 時，不顯示 calendar，手機版要放大才好按
- [x] 「專案擁有者」的顯示可以考慮換位置
    - [x] 使用者沒有名字要提示「無名」，或將 user.name 設為 nill: false
- [x] 查看他人專案時，「非專案擁有者」不顯示「專案編輯」按鈕
- [x] edit project 之後要即時更新（turbo_stream）

● project kanban
- [x] 「新增列表」按鈕
    - [x] 要更明顯、像個按鈕
    - [x] 去掉 shadow
- [x] 顯示橫向滾輪

● project calendar
- [x] 手機版時，修正 full calendar header 破版

# list
● list _list
- [x] 看看要不要 底色用 list.color 的相似色
- [x] 「新增任務」按鈕要像個按鈕

● list new
- [ ] JS controller color_picker_controller
    - [ ] 顏色空白（透明）
        - [x] 選項一：有預設顏色
        - [ ] 選項二：hover 的色票 input 欄位要有「填入顏色」的 placeholder

# task
● task _task
- [x] 修正地址和優先級標籤的破版
    - [x] 優先級放到卡片右上角
    - [x] task.title 太長會顯示省略為「...」
- [x] 「任務負責人」沒有名字要提示「無名」，或是將 user.name 欄位改為 nill: false
- [x] hover 可以考慮換底色，而不是顯示 border；或是讓 border 是 list.color

● task _new & edit
- [x] 優先級的選項要 i18n

**Comment by AranceLiu** [comment]
「任務負責人」沒有名字要提示「無名」 ->  做 「無指派」 、 「Unassigned」
